### ISSUE TITLE
BUG: Error: Cannot find module 'webpack/lib/node/NodeOutputFileSystem'

### ISSUE THREAD

**Issue by leongaban** [Futuratum/moonholdings.io#40]
After running `npm run dev` the follow error occurs and the script ends.

```
{ Error: Cannot find module 'webpack/lib/node/NodeOutputFileSystem'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/leongaban/projects/Futuratum/moonholdings.io/node_modules/webpack-dev-middleware/lib/fs.js:7:30)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' }
```

This all happened after installing `webpack` locally then trying to setup this webpack plugin in the next.config file: https://github.com/zeit/next.js/issues/805

After realized we should not install webpack since NextJS already handles that, I did removed `webpack` from the package.json file. Then did: `rm -R node_modules && npm i`

Now the project won't run.

**Comment by leongaban** [comment]
Question posted: https://stackoverflow.com/questions/54718758/react-nextjs-app-installed-webpack-then-removed-it-error-cannot-find-module/54718903#54718903

Fix found! https://github.com/webpack/webpack/issues/2131#issuecomment-383017060

```
rm node_module -R
rm package-lock.json (this should be removed)
npm cache verify
npm install
```
